name: vcapp
description: "Test demo application for test vc and REST API'S"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  agora_rtc_engine: ^6.5.3
  permission_handler: ^12.0.1
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon.png"
# flutter pub run flutter_launcher_icons 

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/icon.png
  android_12:
    image: assets/icon/icon.png
#  dart run flutter_native_splash:create 

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
